#!/usr/bin/env python
import os
def commits(x: int):
    for i in range(x):
        os.system(f"echo {i} > data.txt")
        os.system(f"git add data.txt")
        os.system(f"git commit -m='{i}' --date='{i} day ago'")
        os.system("git push")
print(r"""
   _____                         
  / ____|                        
 | |  __  ___ ___  _ __ ___  ___ 
 | | |_ |/ __/ _ \| '_ ` _ \/ __|
 | |__| | (_| (_) | | | | | \__ \
  \_____|\___\___/|_| |_| |_|___/                            
  github.com/kotik06/gcoms
""")
x=int(input("Введите количество коммитов:"))
commits(x)
